### ISSUE TITLE
Redundant code in readme

### ISSUE THREAD

**Issue by garrettw** [jstewmc/get-browser#1]
In your readme, you have:
```php
// instantiate the service
$service = new GetBrowser();

// get the browser
$browser = (new GetBrowser())($userAgent);
```
You're calling `new GetBrowser()` twice, and the object you create and store in `$service` never even gets used.

Might I suggest changing that last line to this if you really want to hold onto the `$service` object:
```php
$browser = $service($userAgent);
```

**Comment by jstewmc** [comment]
Ha! Whoops haha. Thank you for the heads up. I fixed it.
